server:
  port: 8080

spring:
  ai:
    deepseek:
      api-key: sk-785d01cbe19144c29a25e8424fc4c283 # 填写 DeepSeek Api Key, 改成你自己的
      base-url: https://api.deepseek.com # DeepSeek 的请求 URL, 可不填，默认值为 api.deepseek.com
      chat:
        options:
          model: deepseek-chat # 使用哪个模型
          temperature: 0.8 # 温度值

    zhipuai:
      base-url: https://open.bigmodel.cn/api/paas # 智谱 AI 的请求 URL, 可不填，默认值为 open.bigmodel.cn/api/paas
      api-key: 836a2cdc408d4a5fbc02117ce79a354f.oeLkPsEWNtkeEvNG # 填写智谱 AI 的 API Key, 该成你自己的
      chat:
        options: # 模型参数
          model: glm-4-air # 模型名称，使用智谱 AI 哪个模型
          temperature: 0.7 # 温度值

    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode # OpenAI 服务的访问地址，这里使用的第三方代理商：智增增
      api-key: sk-63242340c1c245a5988887649214f086	  # 填写智增增的 API Key, 该成你自己的
      chat:
        options:
          model: qwen-plus # 模型名称
          temperature: 0.7 # 温度值

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
